name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create and Upload Release
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Create a release when a tag is pushed
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release for tag ${{ github.ref }}.
        draft: false
        prerelease: false

    # Upload the executable files (.exe and .x86_64)
    - name: Upload Windows Build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./GameUploader.exe
        asset_name: GameUploader.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux Build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./GameUploader.x86_64
        asset_name: GameUploader.x86_64
        asset_content_type: application/octet-stream
